### ISSUE TITLE
运行bash scripts/webui.sh时，遇到UnicodeDecodeError

### ISSUE THREAD

**Issue by Daniel-Yang-A** [pengxiao-song/LaWGPT#121]
在运行bash scripts/webui.sh时遇到以下错误：

$ bash ./scripts/webui.sh

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin C:\Users\Yang\.conda\envs\lawgpt\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so
C:\Users\Yang\.conda\envs\lawgpt\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
CUDA SETUP: Loading binary C:\Users\Yang\.conda\envs\lawgpt\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.so...
argument of type 'WindowsPath' is not iterable
Traceback (most recent call last):
  File "D:\LaWGPT\webui.py", line 211, in <module>
    fire.Fire(main)
  File "C:\Users\Yang\.conda\envs\lawgpt\lib\site-packages\fire\core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\Yang\.conda\envs\lawgpt\lib\site-packages\fire\core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "C:\Users\Yang\.conda\envs\lawgpt\lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "D:\LaWGPT\webui.py", line 39, in main
    prompter = Prompter(prompt_template)
  File "D:\LaWGPT\utils\prompter.py", line 22, in __init__
    self.template = json.load(fp)
  File "C:\Users\Yang\.conda\envs\lawgpt\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 95: illegal multibyte sequence

看上去像是路径解码出现了问题，但是我不太会解决，可以帮助我一下吗

**Comment by Arc-2023** [comment]
估计得跑在linux物理机上吧
vmware上要配置gpu虚拟化，windows上用git bash运行就会出现这个问题，还会出现GPU不可用的情况

**Comment by CaoYongshengcys** [comment]
我也遇到了这个问题，是在win10+anaconda下安装的

**Comment by YANGtzeRi** [comment]
我有用这个问题，不知道为什么
