### ISSUE TITLE
RuntimeError: unscale_() has already been called on this optimizer since the last update()

### ISSUE THREAD

**Issue by mengqunhan** [pengxiao-song/LaWGPT#124]
**运行bash scripts/train_clm.sh报错** 

50%|████████████████████████████████████████                                        | 1/2 [00:14<00:14, 14.49s/it]Traceback (most recent call last):
  File "train_clm.py", line 261, in <module>
    fire.Fire(train)
  File "/media/cfs/hanmengqun1/.pylib/lib/python3.7/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/media/cfs/hanmengqun1/.pylib/lib/python3.7/site-packages/fire/core.py", line 480, in _Fire
    target=component.__name__)
  File "/media/cfs/hanmengqun1/.pylib/lib/python3.7/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "train_clm.py", line 253, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/media/cfs/hanmengqun1/.pylib/lib/python3.7/site-packages/transformers/trainer.py", line 1649, in train
    ignore_keys_for_eval=ignore_keys_for_eval,
  File "/media/cfs/hanmengqun1/.pylib/lib/python3.7/site-packages/transformers/trainer.py", line 1989, in _inner_training_loop
    args.max_grad_norm,
  File "/media/cfs/hanmengqun1/.pylib/lib/python3.7/site-packages/accelerate/accelerator.py", line 1893, in clip_grad_norm_
    self.unscale_gradients()
  File "/media/cfs/hanmengqun1/.pylib/lib/python3.7/site-packages/accelerate/accelerator.py", line 1856, in unscale_gradients
    self.scaler.unscale_(opt)
  File "/media/cfs/hanmengqun1/.pylib/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 273, in unscale_
    raise RuntimeError("unscale_() has already been called on this optimizer since the last update().")
RuntimeError: unscale_() has already been called on this optimizer since the last update().

**Comment by mengqunhan** [comment]
已解决，更改transformers==4.29.1
