### ISSUE TITLE
bash ./scripts/webui.sh 无法运行

### ISSUE THREAD

**Issue by crazy-canux** [pengxiao-song/LaWGPT#146]
bash ./scripts/webui.sh                                                                                                                                                      ─╯
/home/canche01/.conda/envs/lawgpt/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/canche01/.conda/envs/lawgpt/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Loading checkpoint shards:   0%|                                                                                                                              | 0/2 [00:00<?, ?it/s]/home/canche01/.conda/envs/lawgpt/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.08s/it]
Traceback (most recent call last):
  File "/home/canche01/Canux/LaWGPT/webui.py", line 211, in <module>
    fire.Fire(main)
  File "/home/canche01/.conda/envs/lawgpt/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/canche01/.conda/envs/lawgpt/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/canche01/.conda/envs/lawgpt/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/canche01/Canux/LaWGPT/webui.py", line 200, in main
    gr.inputs.Textbox(
AttributeError: module 'gradio' has no attribute 'inputs'

**Comment by bellarpa** [comment]
AttributeError: module 'gradio' has no attribute 'inputs'
我遇到了和你一摸一样的问题，安装版本是gradio 4.13.0。所以我卸载了4.13.0版本，安装历史版3.50.2就可以继续运行启动了。
pip uninstall gradio
pip install gradio==3.50.2
