### ISSUE TITLE
RuntimeError: MPS does not support cumsum op with int64 input

### ISSUE THREAD

**Issue by 4rayl** [pengxiao-song/LaWGPT#40]
```
Traceback (most recent call last):
  File "/Users/ray/Project/LaWGPT/utils/callbacks.py", line 47, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/Users/ray/Project/LaWGPT/webui.py", line 140, in generate_with_callback
    model.generate(**kwargs)
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/peft/peft_model.py", line 627, in generate
    outputs = self.base_model.generate(**kwargs)
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/generation/utils.py", line 1518, in generate
    return self.greedy_search(
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/generation/utils.py", line 2332, in greedy_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 736, in prepare_inputs_for_generation
    position_ids = attention_mask.long().cumsum(-1) - 1
RuntimeError: MPS does not support cumsum op with int64 input
Traceback (most recent call last):
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/blocks.py", line 1059, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/interface.py", line 632, in fn
    async for output in iterator:
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/ray/.pyenv/versions/3.10.10/lib/python3.10/site-packages/gradio/utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "/Users/ray/Project/LaWGPT/webui.py", line 156, in evaluate
    print(decoded_output)
UnboundLocalError: local variable 'decoded_output' referenced before assignment
``` 

请问是否可以支持 Apple M2 Max 芯片的推理

**Comment by 4rayl** [comment]
已解决，
