### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by rabotone** [pengxiao-song/LaWGPT#62]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\usertemp\AppData\Local\Temp\pip-install-wz75nok1\quantstats_de28e6f2f2214f57a3b180964244d418\setup.py", line 30, in <module>
          with io.open(path.join(here, 'requirements.txt'), encoding='utf-8') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\usertemp\\AppData\\Local\\Temp\\pip-install-wz75nok1\\quantstats_de28e6f2f2214f57a3b180964244d418\\requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

**Comment by Timzer** [comment]
同问
